// REDUX ACTION TYPES
export const TICK = 'TICK'
export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'
export const RESET = 'RESET'


export const FIRSTLOADMENU = 'FIRSTLOADMENU'
export const FIRSTLOADCONTROLMENU = 'FIRSTLOADCONTROLMENU'
export const FIRSTLOADMATERIALS = 'FIRSTLOADMATERIALS'
export const CATEGORYMATERIALS = 'CATEGORYMATERIALS'


export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'


export const OPENMODAL = 'OPENMODAL'
export const CLOSEMODAL = 'CLOSEMODAL'
export const OPENCONFIRMEDMODAL = 'OPENCONFIRMEDMODAL'
export const CLOSECONFIRMEDMODAL = 'CLOSECONFIRMEDMODAL'


export const PAGESWITCHER = 'PAGESWITCHER'
export const GETALLUSERS = 'GETALLUSERS'
export const EDITUSER = 'EDITUSER'
export const SAVEEDITED = 'SAVEEDITED'
export const GETALLROLES = 'GETALLROLES'

export const ALERT = 'ALERT'

export const ALLCATEGORIES = 'ALLCATEGORIES'
export const SAVEEDITEDCATEGORIES = 'SAVEEDITEDCATEGORIES'

export const ALLSUBCATEGORIES = 'ALLSUBCATEGORIES'
export const SAVEEDITEDSUBCATEGORIES = 'SAVEEDITEDSUBCATEGORIES'
export const GETSUBCATEGORIESFORCATEGORY = 'GETSUBCATEGORIESFORCATEGORY'

export const ALLMATERIALS = 'ALLMATERIALS'
export const SAVEEDITEDMATERIALS = 'SAVEEDITEDMATERIALS'