// REDUX ACTION TYPES
export const TICK = 'TICK'
export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'
export const RESET = 'RESET'


export const FIRSTLOADMENU = 'FIRSTLOADMENU'
export const FIRSTLOADMATERIALS = 'FIRSTLOADMATERIALS'
export const CATEGORYMATERIALS = 'CATEGORYMATERIALS'


export const LOGIN = 'LOGIN'


export const OPENMODAL = 'OPENMODAL'
export const CLOSEMODAL = 'CLOSEMODAL'
